project:
  type: website

website:
  title: "firstblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - sample.qmd
format:
  html:
    theme: cosmo
    css: styles.css



